# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr2slack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubSecret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository', models.TextField(unique=True)),
                ('secret', models.TextField()),
            ],
            options={
                'db_table': 'p2t_github_secret',
            },
        ),
    ]
